micronaut:
  application:
    name: micronaut
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
  views:
    freemarker:
      default-encoding: "UTF-8"
